# version: '3'
# services:
#   web:
#     build: .
#     ports:
#     - "80:80"
#     - "3000:3000"
#     volumes:
#     - .:/code
#     - logvolume01:/var/log
#     links:
#     - redis
#   redis:
#     image: redis
# volumes:
#   logvolume01: {}

version: '3'
services:
  nodejs_app:
    container_name: nodejs_app
    image: dilanmorar/nodejs_app
    restart: always
    ports:
      - '3000:3000'
    # connecting app to the database
    environment:
          - DB_HOST=mongodb://mongodb:27017/posts
    links:
      - mongodb3.6
  mongodb:
    container_name: mongodb3.6
    image: dilanmorar/mongodb3.6
    ports:
      - '27017:27017'
